name: Trigger auto deployment for finance-app-gateway

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/finance-app-gateway-AutoDeployTrigger-99e5d182-1689-41fa-924c-87fec1bf7da9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FINANCEAPPGATEWAY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FINANCEAPPGATEWAY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FINANCEAPPGATEWAY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.FINANCEAPPGATEWAY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FINANCEAPPGATEWAY_REGISTRY_PASSWORD }}
          containerAppName: finance-app-gateway
          resourceGroup: projects
          imageToBuild: ghcr.io/finance-app-gateway:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


